steps:
  # Step 1: Create a new Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |

  # Step 2: Dockerize the code and push to the new Artifact Registry
  - name: 'gcr.io/cloud-builders/artifact-registry/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app','.']
  images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$test-application/app'
  - name: 'gcr.io/cloud-builders/artifact-registry/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app']

  # Step 3: Set the deployment name in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "vm-deployment-$(date +%s)" > deployment-name.txt

  # Step 4: Deploy the image to a VM using Deployment Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deployment-manager deployments create $(cat deployment-name.txt) --config vm-deployment.yaml

options:
  env:
    - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'

logsBucket: ncorium-bucket
