steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      "build", 
      "-t", 
      "us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app1:latest",
      "./app1",
    ]

- name: 'gcr.io/cloud-builders/artifact-registry/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app1:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      "build", 
      "-t", 
      "us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app2:latest", 
      "./app2",
    ]

- name: 'gcr.io/cloud-builders/artifact-registry/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app2:latest']

options:
  env:
    - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app1:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/app2:latest'
logsBucket: ncorium-bucket
